### ISSUE TITLE
AWS SDK with C++ language

### ISSUE THREAD

**Issue by HSOOJ** [kookmin-sw/2019-cap1-2019_4#12]
FaceNet 등으로 Bounding Box 가 만들어진 다음,

해당 영역의 Photo를 Crop 하여 AWS S3 쪽으로 전달하기 위해서

AWS SDK with CPP 에 대한 연동 코드가 필요
- https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide

해당 AWS SDK document 를 통해 연동 코드의 작성법을 이해하고 코드 작성하기

**Comment by HSOOJ** [comment]
AWS SDK for C++ 한글화

예제 코드
<https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/cpp>

우분투에서의 기본 패키지 설치
`sudo apt-get install libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev`

AWS-CPP 연동을 위해서는 기본 SDK 코드를 가져와야 한다

> 방법 1 : Visual C++ 의 NuGet 을 이용하여 SDK 가져오기
> 방법 2 : Visual C++ 의 Vcpkg 를 이용하여 SDK 가져오기
> 방법 3 : github 의 소스코드를 가져와 SDK 가져오기 << 우리가 사용할 방법

방법 3의 상세 내용

> `git clone https://github.com/aws/aws-sdk-cpp.git` 으로 코드를 가져옴
> cmake 3.0 이상 버전으로 설치 ( 또는 make 나 msbuild )
> 빌드폴더 생성하기
> `mkdir sdk_build
> cd sdk_build
> cmake <path/to/sdk/source>`
> build 과정이 너무 오래걸린다면 아래의 코드로 s3 SDK 만 설치 가능 *추천
> `cmake -DBUILD_ONLY="s3"`

그 이후에는 AWS 자격 증명의 설정이 필요함

> ~/.aws/credentials 위치에서
> `[default]
> aws_access_key_id = your_access_key_id
> aws_secret_access_key = your_secret_access_key`
> 해당 위치에 나의 access key 와 secret access key 를 넣어야 함

**Comment by HSOOJ** [comment]
C++용 AWS SDK를 사용하는 응용프로그램은 초기화해야함

> `aws/core/Aws.h` : c++용 AWS SKD를 사용하는 모든 응용 프로그램에 이 파일이 포함되어 있어야함
>
> `Aws::InitAPI` : C++용 AWS SDK 초기화
>
> `Aws::ShutdownAPI` : 응용프로그램이 종료되기 전에 SDK를 종료함
>
> 각 메서드는 `Aws::SDKOptions`를 인수로 사용함

```
//skeleton code
#include <aws/core/Aws.h>
int main(int argc, char** argv)
{
   Aws::SDKOptions options;
   Aws::InitAPI(options);
   {
      // make your SDK calls here.
   }
   Aws::ShutdownAPI(options);
   return 0;
}
```

SDK 옵션 설정

Aws :: SDKOptions 인스턴스가 Aws::InitAPI, Aws::ShutdownAPI 메서드에 전달되는데 그 두개가 동일해야함

```
//default logger를 이용해서 로그하기
Aws::SDKOptions options;
options.loggingOptions.logLevel = Aws::Utils::Logging::LogLevel::Info;
Aws::InitAPI(options);
{
    // make your SDK calls here.
}
Aws::ShutdownAPI(options);
// custom memory manager 설치
MyMemoryManager memoryManager;
Aws::SDKOptions options;
options.memoryManagementOptions.memoryManager = &memoryManager;
Aws::InitAPI(options);
{
    // make your SDK calls here.
}
Aws::ShutdownAPI(options);
//default HTTP 클라이언트 팩토리 override
Aws::SDKOptions options;
options.httpOptions.httpClientFactory_create_fn = [](){
        return Aws::MakeShared<MyCustomHttpClientFactory>(
            "ALLOC_TAG", arg1);
    };
Aws::InitAPI(options);
{
    // make your SDK calls here.
}
Aws::ShutdownAPI(options);
```

s3 예제코드

- <https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3.html>

**Comment by HSOOJ** [comment]
CMake로 응용 프로그램 빌드하기
- CMake은 makefile을 만들 수 있는 빌드 도구

프로젝트 설정
1. 소스파일을 저장할 디렉토리 만들기
   ```c++
   mkdir my_example_project
   ```
2. 디렉토리를 열고 CMakeList.txt에 추가하기
   (프로젝트 이름, 실행파일, 소스 파일, 라이브러리 링크)
   ```c++
   # minimal CMakeLists.txt for the AWS SDK for C++
   cmake_minimum_required(VERSION 3.2)
   
   # "my-example" is just an example value.
   project(my-example)
   
   # Locate the AWS SDK for C++ package.
   # Requires that you build with:
   #   -DCMAKE_PREFIX_PATH=/path/to/sdk_install
   find_package(AWSSDK REQUIRED COMPONENTS service1 service2 ...)
   
   # The executable name and its sourcefiles
   add_executable(my-example my-example.cpp)
   
   # The libraries used by your executable.
   # "aws-cpp-sdk-s3" is just an example.
   target_link_libraries(my-example ${AWSSDK_LINK_LIBRARIES})
   ```

CMake 튜토리얼
- https://cmake.org/cmake-tutorial/

CMAKE_PREFIX_PATH 설정 (선택 사항)
- CMake는 aws-sdk-cpp-config.cmake의 위치를 알아야함
- CMAKE_PREFIX_PATH를 하면 응용프로그램을 다시 빌드할때마다 경로를 입력할 필요 없음

설정 방법(linux)
`export CMAKE_PREFIX_PATH=/path/to/sdk_build_dir`

CMake로 빌드하기
1. 빌드 할 디렉토리 만들기
   `mkdir my_project_build`
2. 디렉토리를 열고 cmake 실행
   `cd my_project_build
   cmake ../my_example_project`
- CMAKE_PREFIX_PATH가 안보이면 -Daws-sdk-cpp_DIR를 이용해서 SDK build 디렉토리 경로에 추가함
  `cmake - Daws-sdk-cpp_DIR=/paht/to/sdk_build_dir ../my_example_project`
3. cmake 빌드
   `make`

**Comment by james-sungjae-lee** [comment]
https://github.com/kookmin-sw/2019-cap1-2019_4/issues/1

해당 이슈로 인하여 AWS-CPP Connection 이 아닌 AWS-Python Connection 으로 변경됨에 따라

현재 이슈를 close 한다.
