### ISSUE TITLE
EC2와 RDS 연결하기

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#2]
RDS에 데이터 올려보고 
EC2인스턴스에서 RDS데이터 받아오는 것 완료하기

**Comment by Jisoo-Min** [comment]
1. RDS 인스턴스 생성
![스크린샷 2019-03-10 오후 2 28 12](https://user-images.githubusercontent.com/24731075/54081036-c7c42800-4340-11e9-8f8c-2299f3349caa.png)

2. RDS 접속
`mysql --host=[엔드포인트] --port=[포트넘버] --user=[마스터사용자] --password=[마스터암호]`

3. EC2접속
Ubuntu image 사용해서 생성
`ssh -i pem키 ubuntu@[IPv4 퍼블릭 IP 또는  퍼블릭 DNS]`

**Comment by Jisoo-Min** [comment]
* 주의사항
pem은 region마다 존재하니
같은 region에서 pem과 ec2가 작동

**Comment by Jisoo-Min** [comment]
ec2에서 rds접속하려면 rds보안그룹 인바운드 규칙에 ec2 보안 그룹이 설정되어있어야함.

우리의 경우 ec2에서 mysql로 rds 에 연결해야하니 
![스크린샷 2019-03-10 오후 2 22 29](https://user-images.githubusercontent.com/24731075/54081002-0d342580-4340-11e9-8bbf-c3c2b2387a6f.png)
MYSQL유형에 소스를 EC2 인스턴스에 적용한 보안그룹ID를 추가해야함

+) 추가로 EC2에서는 외부인 접근 방지를 위해 
인바운드 규칙에서 SSH접근을 내ip로 지정하여, 접속가능한 환경에서 미리 추가해서 사용하기!!!

**Comment by Jisoo-Min** [comment]
**ec2인스턴스에서 파이썬으로 rds데이터 가져오는 process**
[ec2-rds mysql.pdf](https://github.com/kookmin-sw/2019-cap1-2019_4/files/2949087/ec2-rds.mysql.pdf)

**Comment by aaa0265** [comment]
ec2에 연결한 뒤 python을 사용하기 위한 환경설정을 해야합니다.   

[ec2_python_환경설정.pdf](https://github.com/kookmin-sw/2019-cap1-2019_4/files/2951007/ec2_python_.pdf)
