### ISSUE TITLE
 Jetson Tx1 -  aws s3 연동 error

### ISSUE THREAD

**Issue by HSOOJ** [kookmin-sw/2019-cap1-2019_4#23]
Jetson TX1 에서 aws s3 의 bucket list는 오류 없이 잘 실행되지만 create_bucket, upload_file 과 같이 bucket 의 내용을 수정하려고 하는 경우에는 다음과 같은 error가 발생한다.

![s3 error](https://user-images.githubusercontent.com/20984428/55271311-29e3cd80-52ee-11e9-82f9-ab0385884345.png)

**Comment by james-sungjae-lee** [comment]
boto3.exceptions.S#UploadFailedError accessdenied 로 찾아본 결과, 기본 환경 설정 중 문제가 생겼을 가능성이 있음. 

https://stackoverflow.com/questions/40416452/upload-file-to-aws-s3-using-boto3-with-full-access-permissions?rq=1

해당 자료를 찾아보고 권한 설정등에 문제가 있거나, access key 를 새로 발급받아 테스트해 볼 필요가 있음

또한 에러 메세지에 python2.7 를 이용하는 것으로 나타나 있는데, 이는 기존의 테스트 환경과 다른 것으로 확인됨. 이를 이전과 같은 환경으로 테스트 하기 위해 python3 로 설정하여 진행해볼 필요가 있음.

**Comment by HSOOJ** [comment]
access key 를 잘못 설정하여 생긴 문제였다..!
