### ISSUE TITLE
ReadMe.md 이미지 수정

### ISSUE THREAD

**Issue by james-sungjae-lee** [kookmin-sw/2019-cap1-2019_4#27]
readme 에 적힌 Architecture 에 대한 설명 이미지가 저화질로 정확하게 알아볼 수 없는 상태이다

이를 해결하기 위해 기존의 저화질 이미지를 고화질 이미지로 대체할 필요가 있다.

**Comment by HSOOJ** [comment]
고화질 이미지로 대체하여 수정하였기 때문에 이슈를 닫도록 하겠습니다.
