### ISSUE TITLE
XGBoost 구현하면서 발생하는 문제점과 해결방법

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#3]
XGboost알고리즘 사용하면서 발생하는 문제점과 해결방법 공유

**Comment by Jisoo-Min** [comment]
IndexError : tuple index out of range
-> 인풋에 들어갈 array의 형태가 안맞아서 생기는 문제 해결하기

![](https://user-images.githubusercontent.com/24731075/51436131-5bc32d00-1cca-11e9-9174-b9517026a870.png)

**Comment by aaa0265** [comment]
model을 만들기 위한 과정 중 fit()에 들어가야하는 파라미터는 input과 output이다.  
여기서 input과 output의 형태가 중요  
  
1. 오류가 났던 data type은 series(1차원 리스트 형태) : 몇 개의 데이터가 한 개로 묶이는지 알 수 없다.
![1](https://user-images.githubusercontent.com/26623522/54067644-c08c1400-4285-11e9-91aa-93f6a26bb6b6.png)
![2](https://user-images.githubusercontent.com/26623522/54067662-e9aca480-4285-11e9-8839-b177c6f4d92a.png)  
  
2.  data type을 DataFrame으로 만들어준다. : 데이터가 한 개씩 확실히 구분.
![3](https://user-images.githubusercontent.com/26623522/54067678-16f95280-4286-11e9-9a89-fd754d9a3764.png)
![4](https://user-images.githubusercontent.com/26623522/54067680-195bac80-4286-11e9-9dfd-0893a8a12c7b.png)
  
3. 오류없이 돌아가는 것을 확인
![5](https://user-images.githubusercontent.com/26623522/54067689-4a3be180-4286-11e9-8e91-c11c44cd3fa3.png)

**Comment by aaa0265** [comment]
<문제점>
1. xgb.XGBClassifier().fit() 와 xgb.train() 의 속도차이가 존재한다. 어떤 것을 쓸 것인지 생각할 필요가 있음.

2. prior set에 order과 product를 합친 테이블을 파라미터로 넣고 model을 만들기 시작하면 테이블 크기가 너무 커서 dead kernel이 됨. 

3. 모델을 만들고 그 모델에 2개의 feature만(사용자 id, 상품 id)가진 table을 넣고 예측을 하려고 했지만 모델을 만들때 넣었던 table의 feature 수와 동일해야한다는 문제점이 생김.

**Comment by aaa0265** [comment]
1. ec2 환경에서 xgboost 설치 과정에 문제가 발생
![xgboost](https://user-images.githubusercontent.com/26623522/55221429-c9508400-524c-11e9-9c7a-788ab6a24eb1.png)

**Comment by aaa0265** [comment]
EC2 환경에서 xgboost를 설치하는 방법
1. git clone https://github.com/dmlc/xgboost.git
2. 1번 완료 후 아래 사진과 같이 진행한다.
![install xgboost](https://user-images.githubusercontent.com/26623522/55231379-c9a94900-5265-11e9-8ba1-9b998051e131.png)

**Comment by aaa0265** [comment]
boosting tree를 시각화하려고 아래코드를 작성하니 그림이 작고 깨짐
```
plot_tree(model)
pyplot.show()
```
![image](https://user-images.githubusercontent.com/26623522/55874956-c485bb80-5bce-11e9-903d-52d42b36ff86.png)

**Comment by aaa0265** [comment]
```
plot_tree(model)

fig = pyplot.gcf()
fig.set_size_inches(20,20)
pyplot.show()
```
위 코드를 작성하니 사이즈가 조절되면서 트리가 깨지지 않음
![image](https://user-images.githubusercontent.com/26623522/55875046-057dd000-5bcf-11e9-8c8e-56baeaa30c07.png)
