### ISSUE TITLE
회의록 날짜와 filename 의 mismatch

### ISSUE THREAD

**Issue by james-sungjae-lee** [kookmin-sw/2019-cap1-2019_4#31]
upload_picture branch 의 

https://github.com/kookmin-sw/2019-cap1-2019_4/blob/upload_pictures/doc/%ED%9A%8C%EC%9D%98%EB%A1%9D/2019_04_02.md

파일에서 filename 은 2019_04_02 이지만 실제 회의 날짜는 2019_04_01 임
이에 대해 수정이 필요함.

**Comment by james-sungjae-lee** [comment]
해당 회의록 filename 이 2019_04_01 로 수정된 다음, 

2019_04_02 로 29차 jetson 팀 회의록이 업로드될 예정입니다.

**Comment by james-sungjae-lee** [comment]
29차 회의록의 이미지 업로드를 확인하는 과정에서

28차 회의록에 사용된 이미지의 filename 또한 0402 로 작성되어 있는 것을 발견함.

해당 filename 수정이 필요할 것으로 보임.

**Comment by aaa0265** [comment]
28차 회의 날짜는 4월 2일로 수정하였습니다.
회의록에 사용된 이미지는 0402가 맞는 것으로 수정할 필요는 없고, 동일한 날짜로 업로드될 사진들은 날짜 뒤에 번호를 붙여서 올리면 될 거 같습니다.
