### ISSUE TITLE
광고 띄울 웹 만들기

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#44]
로컬에서 광고 띄울 웹 만들기!
기본 구조 + 꾸미기

**Comment by Jisoo-Min** [comment]
일단 기본적으로 보여줄 것
광고이미지, 제품명, 제품 분류(위치로 대신 하도록)

@HSOOJ  생각나는 아이디어 있으면 알려쥬시길!!! ㅎㅅㅎ

**Comment by Jisoo-Min** [comment]
`open -a "Google Chrome" ./test.html` 로 하면 Chrome으로 새로고침 처럼 되면서 웹 열림!!

**Comment by james-sungjae-lee** [comment]
https://beomi.github.io/2017/02/27/HowToMakeWebCrawler-With-Selenium/

하나의 Python 코드 내에서 서로 다른 웹페이지에 접근하고자 한다면, 

chrome driver 를 selenium 에서 사용하여 driver.get ( url ) 으로 접근 가능함.

**Comment by Jisoo-Min** [comment]
@odobenuskr  아이거 광고 보여줄 웹 디자인 말한거였어요..!!!ㅇㅅㅇ

**Comment by Jisoo-Min** [comment]
<img src="https://user-images.githubusercontent.com/24731075/57074400-baaf2e00-6d1e-11e9-95fc-a5bc49f663f8.png" width="60%">

**Comment by Jisoo-Min** [comment]
<img src="https://user-images.githubusercontent.com/24731075/57075790-cf8dc080-6d22-11e9-8325-eafaa9f005eb.png" width="60%">

색깔바꿈 ㅎㅎㅎㅎ

**Comment by Jisoo-Min** [comment]
정해진 문구 
Welcome ଘ(੭*ˊᵕˋ)੭*
'황수진' 고객님, '제품이름'은 어떠세요? '제품분류'코너에 준비되어있습니다.

**Comment by HSOOJ** [comment]
정해진 문구 반영
![image](https://user-images.githubusercontent.com/20984428/57177970-b9a80900-6ea4-11e9-8515-807600dd2a46.png)

**Comment by Jisoo-Min** [comment]
@HSOOJ  boldㅊㅔ로 바꾸면 어떨까? ㅎㅅㅎ
두번째줄도 ㅎㅎㅎ

**Comment by Jisoo-Min** [comment]
그리고그 코너랑 그런거는 나중에 지원이한테서 결과나오면 완성시켜줄수있을듯ㅎㅎㅎ

**Comment by HSOOJ** [comment]
@jiisoo 첫번째줄은 html 에서 <.h2> 쓴거고 두번째줄은 js 에서 색 있는거만 <.b> 한거얌!

**Comment by Jisoo-Min** [comment]
폰트모음이다
https://fonts.google.com/specimen/Jua
https://fonts.google.com/specimen/Black+Han+Sans

**Comment by HSOOJ** [comment]
![image](https://user-images.githubusercontent.com/20984428/57664923-edb5c380-7634-11e9-835c-4fc4c37eeea9.png)
이런 느낌으로 만들고싶다~ (피피티로 만듦)

**Comment by Jisoo-Min** [comment]
수진아그거 각깍 json에 

```
Item={
        'user_id': user_id,
        'update_ver' : 1,
        'product_id': product_id,
        'product_name' : product_name,
        'aisle_name' : aisle_name,
        'bucket_url': "https://s3-us-west-2.amazonaws.com/kmu-ads-bucket/"+ str(product_id) + ".png"
        }
```
이렇게있으니까 필요한거받아가면댄다
@HSOOJ

**Comment by HSOOJ** [comment]
@jiisoo update_ver는 머야?

**Comment by Jisoo-Min** [comment]
아그거 지금 몇번째로 데이터 올린건지 ㅇㅅㅇ 
일주일마다 업데이트하기로햇는데  그거마다 버전얼라가는건데 너눈 무시해두대!!!

**Comment by HSOOJ** [comment]
![image](https://user-images.githubusercontent.com/20984428/57744470-515af200-7704-11e9-9a97-99d5ad2cb171.png)
광고 화면 초안 최종본 ㅎ_ㅎ
전시할 때 데모 환경(모니터 크기, 웹 크기) 파악 후 거기에 맞춰서 수정할 예정
