### ISSUE TITLE
api로부터 받은 data를 python에서 읽기 오류

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#46]

**Comment by Jisoo-Min** [comment]
API를 통해 광고로 보낼 정보를 받아왔으나, python에서 제대로 element들을 가져올 수 없음
<img width="617" alt="스크린샷 2019-05-03 오후 5 56 03" src="https://user-images.githubusercontent.com/24731075/57127918-cb1de200-6dcc-11e9-92b3-426499ac1b94.png">

**Comment by HSOOJ** [comment]
`response[0]`
![image](https://user-images.githubusercontent.com/20984428/57127813-7f6b3880-6dcc-11e9-9e9b-1a0e23734b6d.png)

`response.text[0]`
![image](https://user-images.githubusercontent.com/20984428/57127901-c1947a00-6dcc-11e9-868f-bb5a4e7eb5ff.png)

**Comment by HSOOJ** [comment]
`response.text['user_id']`
![image](https://user-images.githubusercontent.com/20984428/57127992-03252500-6dcd-11e9-94e6-829b0ca0f1e6.png)

**Comment by Jisoo-Min** [comment]
`response.json()['user_id']` 
이렇게 해바~~

**Comment by HSOOJ** [comment]
오 된다 ㅎㅅㅎ
![image](https://user-images.githubusercontent.com/20984428/57128065-3ebfef00-6dcd-11e9-9526-a7b00c9f25ae.png)
