### ISSUE TITLE
광고이미지 S3에 올리기

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#49]

**Comment by Jisoo-Min** [comment]
HELPER @HSOOJ @aaa0265

**Comment by Jisoo-Min** [comment]
현재 300개 정도 광고이미지 로드됨  + 추가 광고이미지는 최종 결과에 맞춰 업로드

**Comment by Jisoo-Min** [comment]
https://docs.google.com/spreadsheets/d/1v51ueixiCRPUFNlyfbBQISrS6eodlZB17leqfwh69nk/edit?usp=sharing

**Comment by HSOOJ** [comment]
제품 사진 대신에 제품 광고 사진을 찾아서 하는것이 좋을것 같습니다용

**Comment by Jisoo-Min** [comment]
예이예이 그럽시다융

**Comment by Jisoo-Min** [comment]
추천 결과에 맞는 광고이미지를 찾고 
고객에게 바로바로 매칭될 수 있도록 데이터 만들어놓음!

<img src="https://user-images.githubusercontent.com/24731075/58012049-8b762a80-7b2e-11e9-9d1e-cd7ae58a5fcb.png" width="60%">

**Comment by Jisoo-Min** [comment]
팀원 5명에 대한 매칭 정보

![image](https://user-images.githubusercontent.com/24731075/58012087-a21c8180-7b2e-11e9-83e6-d5f263a91bdc.png)

**Comment by Jisoo-Min** [comment]
팀원에 대한 광고정보와 ㄱ해당광고이미지,

추천 결과에 따른 광고이미지 (사람들이 직접 등록해볼 수 있도록) 모두 저장함!
