### ISSUE TITLE
Evaluation기록하기!!

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#50]
evaluation 할때마다 수치 기록하기

**Comment by aaa0265** [comment]
First 
- dep_prob : 각 유저당 해당 대분류의 상품을 살 확률
- aisle_prob : 각 유저당 해당 소분류의 상품을 살 확률 
- dow_prob :  각 유저당 월~일에에 구매할 확률 
- hour_prob : 각 유저당 0~24시에 구매할 확률 
- organic : 각 유저당 organic 상품을 구매할 확률

위 5개의 feature를 통한 evaluation 결과 
private : 0.24738
public : 0.24899

**Comment by aaa0265** [comment]
second

- dep_prob : 각 유저당 해당 대분류의 상품을 살 확률
- aisle_prob : 각 유저당 해당 소분류의 상품을 살 확률 
- dow_prob :  각 유저당 월~일에에 구매할 확률 
- hour_prob : 각 유저당 0~24시에 구매할 확률 
- organic : 각 유저당 organic 상품을 구매할 확률
- latest_xxx : 제일 최근 구매한 상품 개수와 그 상품이 재구매 된 횟수 (2개)

위 7개 feature를 통한 evaluation 결과
private : 0.34293
public : 0.34564

**Comment by aaa0265** [comment]
Third 


- dep_prob : 각 유저당 해당 대분류의 상품을 살 확률
- aisle_prob : 각 유저당 해당 소분류의 상품을 살 확률 
- dow_prob :  각 유저당 월~일에에 구매할 확률 
- hour_prob : 각 유저당 0~24시에 구매할 확률 
- organic : 각 유저당 organic 상품을 구매할 확률
- latest_xxx : 제일 최근 구매한 상품 개수와 그 상품이 재구매 된 횟수
- timezone : 0~24시간을 4개의 범위로 나눠 label를 설정한 것

두번째 eval에 한 가지(timezone)를 추가한 것
private : 0.34128
public : 0. 34404 
-> timezone이 추가되면서 결과가 조금 내려감.

**Comment by aaa0265** [comment]
스크린 캡쳐로 설명 대체
![01](https://user-images.githubusercontent.com/26623522/57677591-26b85d00-7662-11e9-8387-e2f01b0ab0ab.png)

**Comment by aaa0265** [comment]
![02](https://user-images.githubusercontent.com/26623522/57677669-510a1a80-7662-11e9-9a58-cee02b45b235.png)

**Comment by aaa0265** [comment]
![스크린샷, 2019-05-14 16-07-22](https://user-images.githubusercontent.com/26623522/57677693-61ba9080-7662-11e9-9243-4419e45d474f.png)

>현재까지 최근 구매 기록을 살피는 함수와 order_ratio_bychane()를 사용하여 만든 feature가 있을 때가 제일 높은 기록을 가지고 있음.

**Comment by aaa0265** [comment]
model 생성시 최대 depth을 줄이면 정말 작은 값이지만 증가하는 것을 볼 수 있다.
![비교](https://user-images.githubusercontent.com/26623522/57691235-9dfbea00-767e-11e9-8ef6-a5caab2db038.png)
-> 첫번째와 다섯번째 값을 통해 알 수 있음

**Comment by aaa0265** [comment]
reordered_xxx ,  order_ratio_bychance 함수와 model depth 5로 줄인 것이 0.36302로 제일 높아졌다.

**Comment by Jisoo-Min** [comment]
기록 그래프로 공유하고 이슈 닫기~

**Comment by aaa0265** [comment]
![그래프](https://user-images.githubusercontent.com/26623522/58089613-3a366b80-7c00-11e9-843d-3780a296569e.png)
17번 제출 score 그래프 입니다.
