### ISSUE TITLE
Flex Ads Demo 를 위한 TX2 (Camera) 설치 방법의 논의

### ISSUE THREAD

**Issue by james-sungjae-lee** [kookmin-sw/2019-cap1-2019_4#51]
Flex Ads Demo 를 위해서, 일정한 높이에 카메라가 있어야 정확한 인식이 가능하다

이를 위해서 물리적으로 카메라를 바닥에서 1.7~1.8m 위치에 있도록 설치해야 한다.

대표적인 방법으로, 삼각대를 이용하여 TX2 를 설치할 수 있으며

이 때 TX2 를 통째로 올려놓거나, Camera 의 extension cable 을 이용하여 Camera Module 만 올려놓을 수 있다

사전조사로 Extension Cable 의 설치가 어떻게 가능한지에 대해 알아보도록 한다.

**Comment by HSOOJ** [comment]
검색해보았을 때 TX1의 카메라는 'Omnivision OV5693 -5MP' 임을 알 수 있었다
https://www.youtube.com/watch?v=mJBA1Y4BlXY
https://www.jetsonhacks.com/2015/11/13/nvidia-jetson-tx1-module-connector/

**Comment by HSOOJ** [comment]
![image](https://user-images.githubusercontent.com/20984428/57462335-a08fc580-72b3-11e9-9fd1-dd9fb2b39657.png)
이걸보면 micro coaxial cable 같은 케이블을 이용하는것 같은데 잘 모루겠다.....ㅠㅂㅠ

**Comment by james-sungjae-lee** [comment]
삼각대 위에 TX2 를 통째로 올려놓는 것은, 고정을 위한 너츠가 존재하지 않아 무리가 있다.

onboard camera 를 연장하는 것 또한 위의 상황으로 보아 무리가 있다

이에 usb 를 이용한 logitech 의 추가 camera 를 사용하는 것을 고려한다.

이 경우, 삼각대에 설치 가능한 것을 확인한 상태이며 detectnet-camera 에서 camera port 를 변경해 줄 필요가 있다.

현재는 해당 camera 를 빌려서 테스트 하는 상태이며, 가능하다면 usb hub 와 함께 구매할 필요가 있다.

![IMG_0757](https://user-images.githubusercontent.com/20024627/57836901-a67a2f00-77fc-11e9-98b8-b94f12e90585.jpeg)

![IMG_0758](https://user-images.githubusercontent.com/20024627/57836939-bd208600-77fc-11e9-93d3-a2fe03263085.jpeg)

**Comment by james-sungjae-lee** [comment]
얼굴 등록 시스템을 위한 TX1 의 카메라와

얼굴 인식 시스템을 위한 TX2 의 카메라의 2개가 필요하다

얼굴 등록 시스템의 카메라는 Jetson 의 Onboard 로 진행한다 하더라도, 최소 1개가 필요하다

이를 해결하기 위해서 Stable 한 최소 1개의 카메라를 구할 필요가 있으며, 최대 2개의 카메라를 보유하여야 한다.

이에 교수님과 의논 및 학과 사무실에 요청하여 결과적으로 Microsoft 의 LifCam Studio 를 빌릴 수 있었다.

기존의 Logitech C920 보다 화질은 떨어지지만, 정상작동 하는 것을 확인하였다. 

![Image from iOS](https://user-images.githubusercontent.com/20024627/57929262-c9d0d700-78ed-11e9-8b8f-f6d45cfde3c6.jpg)

두 카메라 모두 삼각대에 설치 가능하도록 만들어져 있으며, 데모 시행에서는 삼각대를 활용하도록 한다.

이로써 TX1 / TX2 카메라 설치 방법에 대한 논의는 마치고 이슈를 닫도록 한다.
