### ISSUE TITLE
GitHub 사용하면서 발생하는 문제

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#6]
github 공동작업하면서 발생하는 error 등등 공유하기

**Comment by james-sungjae-lee** [comment]
Github 에 odobenuskr 계정이 아닌, Sungjae 계정으로 올라감.

terminal 에서의 작업 과정은 다음과 같음

git clone https://github.com/kookmin-sw/2019-cap1-2019_4
> git ignore 파일의 작성 / 특정 폴더의 생성 / 예제 코드의 작성
git pull
git checkout -b face_testcode
git add .
git commit -m 'aws cpp testcode'
git push origin face_testcode

예상되는 원인으로는, local PC 에 다른 github 계정이 존재하여, branch 가 생성되고 push 된 것으로 생각해볼 수 있음. 원인을 확인하기 위해 다른 github repo 에 동일한 환경에서 master push / branch push 를 테스트해볼 필요가 있음.

**Comment by HSOOJ** [comment]
master push를 제한한 상태에서 직접 master에 push해서 에러 발생

![github error](https://user-images.githubusercontent.com/20984428/54083940-c5c48e00-436d-11e9-9006-64025a6eda14.png)

해결
- Branch를 생성하여 pull request를 한 후 git merge 해서 git push 완료
> 참고링크
> - https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches
> - https://rogerdudler.github.io/git-guide/index.ko.html

**Comment by HSOOJ** [comment]
![github push error](https://user-images.githubusercontent.com/20984428/54736847-6e85af80-4bf0-11e9-8024-57097aa0ba28.png)

**Comment by Jisoo-Min** [comment]
master  merge가 1-2명의 승인이 나야 될 수 있게 했는데, 어느 순간 브랜치에서 push가 안됨!!
그래서 master만 branch rule적용함!!

**Comment by Jisoo-Min** [comment]
https://kookmin-sw.github.io/2019-cap1-2019_4 
깃허브 홈페이지를 위해 index.md를 작성했는데  그림이 로딩이 안됨
![image](https://user-images.githubusercontent.com/24731075/56091299-3bc99100-5ee8-11e9-9997-16a1c4cfab06.png)
![image](https://user-images.githubusercontent.com/24731075/56091319-5865c900-5ee8-11e9-9ebc-bcb570460f4c.png)

**Comment by Jisoo-Min** [comment]
사진이 있는 곳의 url을 가져와 사진을 .md로 넣었었는데 위와 같이 깨져서 절대 경로로 넣어줬는데  이마저도 해결책이 아니였다. 
그래서 index.md를 기준으로 상대경로로 img src를 작성했더니 해결되었다.
![image](https://user-images.githubusercontent.com/24731075/56091337-a67acc80-5ee8-11e9-8d59-99be334a30bb.png)

**Comment by Jisoo-Min** [comment]
깃허브 커밋 또는 md에 관한 에러 모두 해결했으므로 이슈 닫음, 필요시 재 오픈
