### ISSUE TITLE
Flex Ads Base Page 의 구성

### ISSUE THREAD

**Issue by james-sungjae-lee** [kookmin-sw/2019-cap1-2019_4#64]
현재는 아무도 인식되지 않은 상황에 대하여, Chrome 의 빈 페이지를 송출하고 있는 상황이다.

여기에 사용자 경험을 높이기 위해서 아무도 인식되지 않은 상황에 Flex Ads 의 기본 페이지를 송출해야 한다.

코드 상으로는 통합 python 코드를 실행하였을 때, 해당 페이지의 html 파일을 호출하도록 driver get 한다.

뿐만 아니라, 기본 페이지에서 무엇을 어떻게 보여줄지에 대해 고민할 필요가 있다

추가적으로 화면 전환 효과, 비회원 출력 화면, 인물이 인식되지 않는 경우의 화면을 고려하여야 한다.

**Comment by Jisoo-Min** [comment]
인식 안될경우에 그럼 user 0번으로 해서 할래요? 
근데 사람인지는 잡히는데 누군지 모르는걸 캐치할수있어융? 그럼 user 0으로 만들어놓을께욤 ㅇㅅㅇ

**Comment by james-sungjae-lee** [comment]
인식 안될 경우의 케이스가 2가지 존재하는데, 

1번 : detectnet-camera facenet 에서 Detect 에 실패한 경우 ( 앞에 사람이 없는 경우 )

2번 : Detect 는 되었지만 Rekognition 에 등록되어 있지 않은 사람인 경우 ( 비회원인 경우 )

여기에 대하여 비회원인 경우에 user_id = 0 으로 만들어 두면 괜찮을 것으로 보입니다.

여기에 해당하는 이미지도 어떤 이미지를 넣을 지에 대해서는 고민해볼 필요가 있습니다.

**Comment by HSOOJ** [comment]
2번 비회원일 경우에는 회원 등록 유도하는 것은 어때요?
"회원 등록하시면 고객님에게 맞는 광고를 제공 받으실 수 있습니다" 느낌으로!

**Comment by Jisoo-Min** [comment]
아
 
구래 구래구래 좋다

**Comment by Jisoo-Min** [comment]
그러면 0번으로 이미지 찾아서 넣어벌게영!!

**Comment by Jisoo-Min** [comment]
이거어떄염
![image](https://user-images.githubusercontent.com/24731075/58079780-c9398880-7bec-11e9-8b61-022eec05d9d7.png)

**Comment by Jisoo-Min** [comment]
2.  이것도가능..
![image](https://user-images.githubusercontent.com/24731075/58080019-4b29b180-7bed-11e9-8c0f-6e0b34092c8a.png)

**Comment by Jisoo-Min** [comment]
<img src="https://user-images.githubusercontent.com/24731075/58080342-03575a00-7bee-11e9-85d1-a9c888d15b04.png" width="60%">

<img src="https://user-images.githubusercontent.com/24731075/58080350-07837780-7bee-11e9-9e70-3d7539ecd162.png" width="60%">

문군구는 수진이 추천대로 아래껄로하면 좋을듯합니다.

**Comment by HSOOJ** [comment]
저는 이런 컨셉을 생각했...!
![image](https://user-images.githubusercontent.com/20984428/58080544-60531000-7bee-11e9-852b-999d88f67b14.png)

**Comment by Jisoo-Min** [comment]
![0](https://user-images.githubusercontent.com/24731075/58088907-9b5d3f80-7bfe-11e9-9054-64aa0899b9b4.png)
이걸로 결정!

**Comment by HSOOJ** [comment]
비회원일때두 회원일때처럼 현재 시간 나오는게 좋을까요? 아니면 없는게 좋을까요?
@odobenuskr  대답점....

**Comment by HSOOJ** [comment]
인식 안될 경우의 2가지 케이스

1번 : detectnet-camera facenet 에서 Detect 에 실패한 경우 ( 앞에 사람이 없는 경우 )
![image](https://user-images.githubusercontent.com/20984428/58250996-94206800-7d9d-11e9-8026-f8b3e0a8e085.png)


2번 : Detect 는 되었지만 Rekognition 에 등록되어 있지 않은 사람인 경우 ( 비회원인 경우 )
 +현재 시간 나오도록 수정함
![image](https://user-images.githubusercontent.com/20984428/58250604-bfef1e00-7d9c-11e9-99a1-87a5ed2894dd.png)

**Comment by HSOOJ** [comment]
회원인 경우의 광고 최종 화면
![image](https://user-images.githubusercontent.com/20984428/58254371-8c64c180-7da5-11e9-9525-f8b02f0a03fe.png)
