### ISSUE TITLE
[ 추가 구현 ] Flex Ads 관리자 웹 페이지 구현

### ISSUE THREAD

**Issue by james-sungjae-lee** [kookmin-sw/2019-cap1-2019_4#77]
시간이 남았을 경우, 추가적으로 구현하면 좋을 관리 페이지에 대해 생각해 보았다.

구현은 선택 사항이며, 구현되었을 경우 어필하기 좋을 것으로 보인다.

웹 페이지 형태로 간단하게 Flex Ads 의 관리 페이지를 만드는 것도 좋아 보인다.

생각중인 기능은 다음과 같다.

1. 로고가 들어간 첫 페이지에서, 관리자 로그인 기능

2. 현재 등록된 DynamoDB 의 회원 데이터들 - 등록, 수정, 삭제 가능 ( 회원 관리 )

3. 회원 넘버를 클릭하였을 경우, S3 에 저장된 회원 얼굴 등록 이미지 중 하나를 보여줌
( S3 에 Directory 별로 저장되었기 때문에 어렵지 않음 )

4. RDS 의 회원 구매내역 데이터들 - 단순 로그 데이터로, 꺼내와 보여주는 기능

5. 그 외의 Jetson 보드의 관리사항 등

현재 생각한 부분은 이 정도이며, 더 좋은 아이디어가 있을 경우 코멘트 바람.

**Comment by Jisoo-Min** [comment]
아근데 이거 하면 좋을꺼같긴하네요.... 목요일까지할수있을까욥..? 아니면 저 ui 도 보여주면 설명할께 너무많으니까 생략할까욥.? ㅇㅅㅇ

**Comment by Jisoo-Min** [comment]
아그리고 4.는 이미 픽스되어있는 구매기록들이라 로그 보여주긴 애매하겟다요!

**Comment by james-sungjae-lee** [comment]
추가적인 관리자 웹페이지는 구현하지 않도록 한다.
