### ISSUE TITLE
데모시 알고리즘 구현 보여줄 용도로 boosting 트리 그림 만들기

### ISSUE THREAD

**Issue by Jisoo-Min** [kookmin-sw/2019-cap1-2019_4#80]

**Comment by aaa0265** [comment]
일반적인 트리 모양
![tree](https://user-images.githubusercontent.com/26623522/58400771-02637400-8097-11e9-9ff0-c734755c67fd.png)

**Comment by aaa0265** [comment]
LR 방향 트리 모양
![다운로드](https://user-images.githubusercontent.com/26623522/58400785-0abbaf00-8097-11e9-9fce-706b335619e9.png)

**Comment by aaa0265** [comment]
텍스트 형식의 트리(round = 100) 
![image](https://user-images.githubusercontent.com/26623522/58443876-e8c23b00-812f-11e9-87b8-b47885ea6a14.png)
![image](https://user-images.githubusercontent.com/26623522/58443894-0099bf00-8130-11e9-8b0a-e18151c555cc.png)

**Comment by aaa0265** [comment]
모델을 어떤 메소드를 쓰느냐에따라 텍스트형, 그림형으로 트리를 출력할 수 있고 없고가 다른 거 같다

**Comment by Jisoo-Min** [comment]
쥬피터이용해서 그림 완료했으므로 이슈 닫음!!! 트리가 워낙커서 고화질이여도 잘 안보일듯함!
